### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by domenmerhar** [domenmerhar/zombie-shooter#1]
- [x] spawn enemies outside camera,
- [x] zombies are faster off camera
- [ ] add athlete zombie,
- [ ] add tank zombie,
- [x] add death,
- [ ] add shotgun,
- [ ] add sniper rifle,
- [ ] add combos,
- [ ] add pickups, 
- [ ] add grenades,
- [ ] add flash grenades,
- [ ] add powerups
